# Generated by Django 4.2.1 on 2023-05-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='managers',
            name='role',
            field=models.CharField(blank=True, default='analize man', max_length=20, null=True),
        ),
    ]
