# Generated by Django 4.2.1 on 2023-05-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_managers_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='managers',
            name='role',
        ),
    ]
